### PR TITLE
build on Python 3.10

### PR DESCRIPTION
**Pull request by skshetry**

### CODE REVIEW

**Comment by skshetry** [comment]
Python 3.10 requires openssl1.1, but having issues installing it for rpm.

**Comment by skshetry** [comment]
yay, it worked. :)

**Comment by skshetry** [comment]
Need to squash-merge after the builds pass. :)

**Comment by skshetry** [comment]
```
DVC version: 2.33.1 (deb)
---------------------------------
Platform: Python 3.10.8 on Linux-5.15.0-1022-azure-x86_64-with-glibc2.27
Subprojects:

Supports:
azure (adlfs = 2022.10.0, knack = 0.10.0, azure-identity = 1.11.0),
...
```

Looks like we don't copy metadata for dvc-projects?

**Comment by skshetry** [comment]
@efiop, should be good to merge now.

**Comment by efiop** [comment]
> Looks like we don't copy metadata for dvc-projects?

Good catch. Indeed, need to add to https://github.com/iterative/dvc/blob/main/scripts/pyinstaller/hooks/hook-dvc.py

**Pull request merged**
